---
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
myTest <-  t.test(values ~ group, data = theData, mu = 0) 

observedTestStat <- myTest$statistic 
  

observedTestStat
```

```{r}
N <- 2000      
permutedTestStats <- rep(NA, N)
for  (i in 1:N ) {
   permutedTest <-   t.test(sample(values) ~ group, data = theData, mu = 0)

   permutedTestStats[i]  <-  permutedTest$statistic 
  
}
hist(permutedTestStats)
abline(v=observedTestStat)
sum(permutedTestStats >= observedTestStat)/N
sum(permutedTestStats <= observedTestStat)/N
```

```{r, eval=FALSE}

# Create the data:
set.seed(1140411)
sample1 <- rnorm(30, 69, 2.5)
sample2 <- rnorm(30, 69, 2.5)
theData <- data.frame(values = c(sample1,sample2), group = rep(c(1,2), each=30))
View(theData)
boxplot(values ~ group, data = theData)

 

# Run the permutation test:

myTest <-  t.test(values ~ group, data = theData, mu = 0)
observedTestStat <- myTest$statistic 

observedTestStat

 

N <- 2000      
permutedTestStats <-  rep(NA, N)
for  (i in 1:N ) {
   permutedTest <- t.test(sample(values) ~ group, data = theData, mu = 0)
   permutedTestStats[i]  <-  permutedTest$statistic 
}
hist(permutedTestStats)
abline(v=observedTestStat)
sum(permutedTestStats >= observedTestStat)/N
sum(permutedTestStats <= observedTestStat)/N

```

```{r}
set.seed(121) #ensure we each get the same set of random values
sample1 <- rnorm(30, 185, 8) #randomly sample n=30 normally distributed values with a mu=185 and sigma=8.
sample2 <- sample1 - rnorm(30, 0, 3.5) #randomly shift each value from sample1, but with mu=0 change overall.
theData <- data.frame(values = c(sample1,sample2), group = rep(c(1,2), each=30), id = rep(c(1:30),times=2)) #load the data into a data set
View(theData)
with(theData, hist(values[group==1] - values[group==2]))

# myTest <- t.test(values ~ group, data = theData, paired = TRUE, mu = 0)
myTest <- t.test(theData$values[theData$group == 1],
                 theData$values[theData$group == 2],
                 paired = TRUE, mu = 0)


observedTestStat <- myTest$statistic

N <- 2000
permutedTestStats <- rep(NA, N)

for (i in 1:N) {
  permutedData <- sample(x=c(1,-1), size=30, replace=TRUE)
  permutedTest <- with(theData, t.test(permutedData*(values[group==1] - values[group==2]), mu=0))
  permutedTestStats[i] <- permutedTest$statistic
}

hist(permutedTestStats)
abline(v=observedTestStat)
sum(permutedTestStats >= observedTestStat)/N
sum(permutedTestStats <= observedTestStat)/N
```


```{r, eval=FALSE}

# Create the data:

set.seed(121)
sample1 <- rnorm(30, 185, 8)
sample2 <- sample1 - rnorm(30, 0, 3.5)
theData <- data.frame(values = c(sample1,sample2), group = rep(c(1,2), each=30), id = rep(c(1:30),times=2))
View(theData)
with(theData, hist(values[group==1] - values[group==2]))

 

# Perform the permutation test:

myTest <-  t.test(theData$values[theData$group == 1],
                 theData$values[theData$group == 2],
                 paired = TRUE, mu = 0)
observedTestStat <- myTest$statistic

 

N <- 2000      
permutedTestStats <-  rep(NA, N)
for  (i in 1:N ) {
   permutedData <- sample(x=c(1,-1), size=30, replace=TRUE)
  permutedTest <- with(theData, t.test(permutedData*(values[group==1] - values[group==2]), mu=0))
  permutedTestStats[i] <- permutedTest$statistic
}
hist(permutedTestStats)
abline(v=observedTestStat)
sum(permutedTestStats >= observedTestStat)/N
sum(permutedTestStats <= observedTestStat)/N

```


